# Generated by Django 3.2.8 on 2022-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lessons_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
