# Generated by Django 3.2.8 on 2022-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratting',
            name='ratting',
            field=models.CharField(max_length=255),
        ),
    ]
